d3.csv("./data/co2/API_EN.ATM.CO2E.KT_DS2_en_csv_v2.csv", d => console.log("co2", d))
d3.csv("./data/methane/API_EN.ATM.METH.KT.CE_DS2_en_csv_v2.csv", d => console.log("methane", d))
d3.csv("./data/population/API_SP.POP.TOTL_DS2_en_csv_v2.csv", d => console.log("population", d))
d3.csv("./data/renewable/API_EG.FEC.RNEW.ZS_DS2_en_csv_v2.csv", d => console.log("renewable", d))
d3.csv("./data/urban_population/API_SP.URB.TOTL_DS2_en_csv_v2.csv", d => console.log("urban", d))